# this file will run a testrunner against the specified image
# run it with:
# docker-compose up --exit-code-from testrunner


sdk_test_server:
    #image: sdk_test_server
    build: .
    environment:
      - MBED_CLOUD_HOST
      - MBED_CLOUD_API_KEY
    volumes:
      - ./results:/testserver/build_logs/
      - ./build/coverage-results:/testserver/build/coverage-results
      - ./test_fixtures:/testserver/test_fixtures
testrunner:
    #build: tests/mbed-cloud-sdk-testrunner
    image: $TESTRUNNER_DOCKER_IMAGE
    environment:
      - TEST_SERVER_URL=http://sdk_test_server:5000
      #folder on test server to get test files from
      - TEST_FIXTURES_DIR=/testserver/test_fixtures
    links:
      - sdk_test_server
    volumes:
      - ./results:/runner/results
      - ./test_fixtures:/runner/test_fixtures
 
