[snippet]
# config for snippet project (https://github.com/ARMmbed/snippet)
input_glob = ['examples/src/main/java/pelion_cloud_sdk/*.java', 'examples/docs/*']
output_dir = 'docs/hla_examples'
log_level=10
language_name = 'java'
comment_prefix = '// '
comment_suffix = ''